Add rtl on main page
sabnzbd/sabnzbd pull request #1776
Opened 2021-02-01 18:19 UTC by puzzledsab

#1430

Can be tested by @IONILz if it builds correctly.

2021-02-01 18:44 UTC, Safihre requested changes
If the changes are this simple it would indeed be a good addition!

2021-02-01 18:44 UTC, Safihre commented on sabnzbd/lang.py
> +    "he": ("Hebrew", "עִבְרִית‎", 1255, 1),
I'd prefer `True`/`False`.

2021-02-01 18:44 UTC, Safihre commented on sabnzbd/interface.py
> +            info["rtl"] = LanguageTable.get(cfg.language(), "en")[3]
Let's introduce a function `is_rtl(lang)` in the `sabnzbd.lang` file. Nicer :)

2021-02-01 23:54 UTC, puzzledsab commented
@Safihre : Do you know why the `<!---->` remains from template tags like `<!--#end if#-->` in `include_menu.tmpl`? It doesn't happen in `main.tmpl`. Is it possible to avoid?

2021-02-02 01:19 UTC, thezoggy commented
We used it as a tactic to safeguard from bad cheetah template leaking stuff and breaking the webpage.

2021-02-02 12:38 UTC, Safihre commented
@puzzledsab @thezoggy I never saw that before.. strange, is that really supposed to be like that?

2021-02-02 13:25 UTC, Safihre commented
Oh right, in the `include_` files you can just use `#` without need for `<!--` and `-->`.

2021-02-03 17:58 UTC, Safihre commented
I don't want to go quite this far. The number of RTL users is less than 0.5% of users! 
Only basic support should be added, because it adds a maintenance burden for years to come.. That's just not worth it.
Unless there's some major things wrong, this is as far as we can go.

2021-02-03 18:33 UTC, puzzledsab commented
@Safihre : Do you mean that any particular changes should be reversed or that I shouldn't add more?

2021-02-04 16:07 UTC, puzzledsab commented
@Safihre : I'm not going to do more changes now. Let me know if you think anything should be reverted.

2021-02-05 14:28 UTC, Safihre commented
I pushed some changes, shifting most of the stuff to the CSS. 
We can add some more of the needed changes there, if needed.
We can also do the config in the same way, to shift the checkboxes using CSS.
If it's really just the checkboxes, it's fine by me. If it really requires HTML changes I don't want to do it..

2021-02-05 17:02 UTC, puzzledsab commented
According to @IONILz it's a clear improvement to add dir=rtl to the config with no other changes, so any CSS changes would be a bonus. It doesn't look so good but the text is probably easier to understand if you read Hebrew.

2021-02-05 17:47 UTC, Safihre commented
Alright, I'll try to fix that asap :)

2021-02-06 14:31 UTC, merged