detect fully encrypted (obfuscated) rars
sabnzbd/sabnzbd pull request #2266
Opened 2022-08-12 19:46 UTC by sanderjo

2022-08-13 09:51 UTC, sanderjo commented
Detecting is working, debug.warning is working, but nzo.fail_msg is not: it gets overwritten in postproc line 645 ...

Tips how to avoid that?

![image](https://user-images.githubusercontent.com/1273502/184478499-e742b06e-e561-447b-95ce-f68ba4a835cd.png)

pycharm debugger:

![image](https://user-images.githubusercontent.com/1273502/184478355-8edcb0be-5586-414e-9cc7-90602d5a2f21.png)

2022-08-16 16:45 UTC, sanderjo commented
Logging is now INFO:

`2022-08-16 18:43:46,223::INFO::[postproc:925] Download Helemaal1 contains a fully encrypted & obfuscated rar-file /home/sander/Downloads/incomplete/Helemaal1/7fafcaa1-a0f4-4330-a889-06a6aa742485. SABnzbd cannot deobfuscate those rar-files`

Result in History is `Completed`, which seems to be SAB-syntactilly correct

Reference NZB (fully encrypted, so both data and headers): https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb__fully_encrypted__meta_password__46d021b78b44.nzb

2022-08-16 18:01 UTC, Safihre requested changes

2022-08-16 18:01 UTC, Safihre commented on sabnzbd/postproc.py
> +            fully_encrypted = rarfile.RarFile(file_to_check, single_file_check=True).filelist() == []
```suggestion
            if not rarfile.RarFile(file_to_check, single_file_check=True).filelist():
```

2022-08-17 00:00 UTC, merged